### PR TITLE
several fixes

### LINKED ISSUE #54: `nimble test` should run test suite
* `nimble test` should run test suite
why?
predictability makes it easier to integrate with tooling, eg https://github.com/nim-lang/Nim/issues/8638
* tests should be in tests instead of under mongo
the layout can be seen using `nimble init`

### LINKED ISSUE #56: nimongo/mongotest.nim fails: ~/.nimble/pkgs/scram-0.1.6/scram/private/utils.nim(17, 13) Error: undeclared identifier: 'MD5Digest'
rnim nimongo/mongotest.nim
nim c --nimcache:/tmp/nim//nimcache/ -o:/tmp/nim//app -r nimongo/mongotest.nim
Hint: used config file '/Users/timothee/git_clone/nim/Nim/config/nim.cfg' [Conf]
Hint: used config file '/Users/timothee/.config/nim/nim.cfg' [Conf]
Hint: used config file '/Users/timothee/.config/nim/config.nims' [Conf]
/Users/timothee/.config/nim/config.nims [config.nims used]
/Users/timothee/git_clone/nim/nimongo/nimongo/mongotest.nim(8, 1) template/generic instantiation from here
/Users/timothee/git_clone/nim/nimongo/nimongo/mongo.nim(25, 1) template/generic instantiation from here
/Users/timothee/.nimble/pkgs/scram-0.1.6/scram/private/utils.nim(17, 13) Error: undeclared identifier: 'MD5Digest'

nim --version
Nim Compiler Version 0.19.9 [MacOSX: amd64]
Compiled at 2018-11-15
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 2eb14bdd41933d3b1b624e48d7513172be1a1e7a
active boot switches: -d:release

### PR DESCRIPTION
**Pull request by timotheecour**
/cc @yglukhov @SSPkrolik
* test/document Bson(string) to string
* fixes #54
* fixes #56
EDIT
* fixes pre-existing bug in .travis.yml (was previously not really testing anything)
* add `nimble test`, `nimble test_ci` commands to test with or without mongod

### CODE REVIEW

**Comment by timotheecour** [comment]
@SSPkrolik @yglukhov I tested locally (based on output from https://travis-ci.com/timotheecour/nimongo/jobs/159187423) , it turns out travis.yml is buggy, can we please merge this and figure out travis after?

```
mkdir /tmp/d02 && cd /tmp/d02
git clone --depth=50 --branch=master https://github.com/timotheecour/nimongo.git timotheecour/nimongo
docker pull yglukhov/nim-base

# passes
docker run -v "$(pwd):/project" -w /project yglukhov/nim-base run "nimble install -y && nim c -r nimongo/bson && nim c -r nimongo/bsontest"

# also passes, with random string
docker run -v "$(pwd):/project" -w /project yglukhov/nim-base run "nimble install -y && nim c -r nimongo/bson && nim c -r adfasfjalfjaslfjasdlfjalsjfalsjfasljfalsdfj"
```

**Comment by timotheecour** [comment]
@SSPkrolik @yglukhov
PTAL, I fixed travis, there was a pre-existing bug (run vs bash); also I adapted travis to run `nimble test_ci` so we can test both `nimble test` (locally, if there's a mongod server) vs `nimble test_ci`
- [ ] in a future PR, we should make travis run `nimble test` and add dependency on mongod in travis

**Comment by timotheecour** [comment]
ping

**Comment by SSPkrolik** [comment]
@timotheecour thanks a lot for the contribution!

**Pull request merged**
